### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'strava_tokens.json'

### ISSUE THREAD

**Issue by a-nigro** [RDNelson00/Strava-Stream-#18]
Getting following error when running:

```
D:\anigro\Strava Dashboard - PowerBI\Strava-Stream->python _Main.py
Auth code from environment: None
Authorization found. Checking token status...
Traceback (most recent call last):
  File "D:\anigro\Strava Dashboard - PowerBI\Strava-Stream-\_Main.py", line 37, in <module>
    expiry = get_token_expiry()
  File "D:\anigro\Strava Dashboard - PowerBI\Strava-Stream-\_Main.py", line 20, in get_token_expiry
    with open(token_file, 'r') as f:
         ~~~~^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'strava_tokens.json'
```

**Comment by RDNelson00** [comment]
@a-nigro, sorry about that.

Please pull my latest changes. I updated the Main script to handle the missing token file. It should auto-generate one now.

Before you run the program again, **please** delete the "auth_code" entry in the .env. The application needs to re-authenticate before it requests a new token file.

Thank you for using my repo and let me know if it worked!
